sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    packages:
      - gcc
      - libmicrohttpd-dev
      - libmicrohttpd10
      - libsqlite3-dev
      - sqlite3
      - libjson-c-dev
      - libjson-c2
      - cmake
script:
  - ln -s /usr/lib/x86_64-linux-gnu/libmicrohttpd.so.10 /usr/lib/x86_64-linux-gnu/libmicrohttpd.so
  - mkdir build && cd build
  - cmake ../
  - make
