sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    packages:
      - gcc
      - libmicrohttpd-dev
      - libsqlite3-dev
      - libjson-c-dev
      - cmake
script:
  - mkdir build && cd build
  - cmake ../
  - make
